package com.mycompany.myapp;
import com.codename1.ui.Toolbar;
import com.codename1.system.Lifecycle;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.mycompany.myapp.screens.CategorieScreeen;
import com.mycompany.myapp.screens.AjoutCategoryScreen;
import com.mycompany.myapp.screens.AjoutServiceScreen;
import com.mycompany.myapp.screens.ServiceScreens;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication extends Lifecycle{

    CategorieScreeen categorieScreen;
    AjoutCategoryScreen ajoutCategoryScreen;
    ServiceScreens serviceScreens;
    AjoutServiceScreen ajoutServiceScreen;

    @Override
    public void runApp() {
        
      categorieScreen = new CategorieScreeen(this);
      ajoutCategoryScreen = new AjoutCategoryScreen (this);
      categorieScreen.show();
      serviceScreens = new ServiceScreens(this);
      ajoutServiceScreen = new AjoutServiceScreen(this);
      serviceScreens.show();
      
      
      
    
     
    }
    public void showForm(Form form){
        form.show();
         
    }
    public void addDrawerMenu(Form form){
        Toolbar drawer=form.getToolbar();
            if (drawer == null) {
            drawer = new Toolbar();
            form.setToolbar(drawer);
        }
      
          drawer.addMaterialCommandToSideMenu("CATEGORY",FontImage.MATERIAL_DASHBOARD, e->{showForm(categorieScreen);});
          drawer.addMaterialCommandToSideMenu("ADD CATEGORY",FontImage.MATERIAL_DASHBOARD, e->{showForm(ajoutCategoryScreen);});
          drawer.addMaterialCommandToSideMenu("SERVICE",FontImage.MATERIAL_DASHBOARD, e->{showForm(serviceScreens);});
          drawer.addMaterialCommandToSideMenu("ADD Service",FontImage.MATERIAL_DASHBOARD, e->{showForm(ajoutServiceScreen);});
          
          
    }
    
    
    
    
    
    
  
}
